server:
  port: 8000
  shutdown: graceful

spring:
  application:
    name: my-space-jarvis
  config:
    import: classpath:application-mysql.yaml, classpath:application-redis.yaml
  profiles:
    group:
      dev: app-dev, mysql-dev, redis-dev
      test: app-test, mysql-test, redis-test
      prod: app-prod, mysql-prod, redis-prod
    default: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null

---
spring:
  config:
    activate:
      on-profile: app-dev

---
spring:
  config:
    activate:
      on-profile: app-test

---
spring:
  config:
    activate:
      on-profile: app-prod