spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my_space?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000

---
spring:
  config:
    activate:
      on-profile: mysql-dev

---
spring:
  config:
    activate:
      on-profile: mysql-test

---
spring:
  config:
    activate:
      on-profile: mysql-prod